### ISSUE TITLE
vim-plug not listed in plugin managers

### ISSUE THREAD

**Issue by oj-lappi** [rockerBOO/awesome-neovim#1031]
Wondering why the, afaik, most popular vim/nvim plugin manager, vim-plug, is not listed in plugin managers.

https://github.com/junegunn/vim-plug has more than three times as many github stars as lazy.nvim, which is the plugin manager with most stars in the list here.

**Comment by fsouza** [comment]
First item in the check list: https://github.com/rockerBOO/awesome-neovim/blob/HEAD/.github/pull_request_template.md

**Comment by oj-lappi** [comment]
Please expand that explanation, do you mean that vim-plug is not on the list because it also supports vim? 

vim-plug is a big part of the eco-system, most of the plugins listed in this repo give examples for installing using vim-plug. I would hope for there to be a well-founded reason for leaving it out.

**Comment by thetic** [comment]
> The plugin is specifically built for Neovim, or if it's a colorscheme, it supports treesitter syntax

This is clearly not true for vim-plug.

**Comment by oj-lappi** [comment]
But it's the plugin manager most people would use to install these neovim plugins. It is weird and arbitrary to leave it out. Somehow the fact that vim-plug supports both vim and neovim is a reason not to list it?

And this criterion that it be designed only for neovim is not mentioned in the readme at all. If vim-plug can't be added to the list, can it at least be mentioned more prominently that parts of the ecosystem that also support vim are not listed.

I use neovim every day and just recently came across this repo looking for what the current ecosystem looks like. I was extremely confused when it was not listed. My first thought was that vim-plug was somehow outdated or considered bad practice, and I had to double check what the status of it was.

**Comment by tan-wei** [comment]
@oj-lappi The repo is "awesome plugins sepcial for Neovim".

**Comment by tversteeg** [comment]
See #574.

**Comment by oj-lappi** [comment]
Ok, it seems the readme's description of the repo is stale then.
