### ISSUE TITLE
Out-of-date plugin entries

### ISSUE THREAD

**Issue by m15a** [rockerBOO/awesome-neovim#1146]
Hello,

I've found a number of plugins changed their owner and/or repository name as shown below. I'd like to make PRs for each of them one by one ~~, or a bulk PR if it is acceptable,~~ later.

1. [`Everblush/everblush.nvim`](https://github.com/Everblush/everblush.nvim):
     - Repository name changed: `everblush.nvim` -> `nvim`
1. [`Junnplus/nvim-lsp-setup`](https://github.com/Junnplus/nvim-lsp-setup):
    - Owner name changed: `Junnplus` -> `junnplus`
     - Repository name changed: `nvim-lsp-setup` -> `lsp-setup.nvim`
1. [`NFrid/due.nvim`](https://github.com/NFrid/due.nvim):
    - Owner name changed: `NFrid` -> `nfrid`
1. [`NFrid/markdown-togglecheck`](https://github.com/NFrid/markdown-togglecheck):
    - Owner name changed: `NFrid` -> `nfrid`
1. [`NFrid/treesitter-utils`](https://github.com/NFrid/treesitter-utils):
    - Owner name changed: `NFrid` -> `nfrid`
1. [`NTBBloodbath/rest.nvim`](https://github.com/NTBBloodbath/rest.nvim):
    - Owner name changed: `NTBBloodbath` -> `rest-nvim`
1. [`Pocco81/AutoSave.nvim`](https://github.com/Pocco81/AutoSave.nvim):
    - Owner name changed: `Pocco81` -> `pocco81`
     - Repository name changed: `AutoSave.nvim` -> `auto-save.nvim`
1. [`Pocco81/DAPInstall.nvim`](https://github.com/Pocco81/DAPInstall.nvim):
    - Owner name changed: `Pocco81` -> `pocco81`
     - Repository name changed: `DAPInstall.nvim` -> `dap-buddy.nvim`
1. [`Pocco81/HighStr.nvim`](https://github.com/Pocco81/HighStr.nvim):
    - Owner name changed: `Pocco81` -> `pocco81`
     - Repository name changed: `HighStr.nvim` -> `high-str.nvim`
1. [`Pocco81/TrueZen.nvim`](https://github.com/Pocco81/TrueZen.nvim):
    - Owner name changed: `Pocco81` -> `pocco81`
     - Repository name changed: `TrueZen.nvim` -> `true-zen.nvim`
1. [`RRethy/nvim-base16`](https://github.com/RRethy/nvim-base16):
     - Repository name changed: `nvim-base16` -> `base16-nvim`
1. [`altermo/nxwm`](https://github.com/altermo/nxwm):
     - Repository name changed: `nxwm` -> `nwm`
1. [`beauwilliams/focus.nvim`](https://github.com/beauwilliams/focus.nvim):
    - Owner name changed: `beauwilliams` -> `nvim-focus`
1. [`ckolkey/ts-node-action`](https://github.com/ckolkey/ts-node-action):
    - Owner name changed: `ckolkey` -> `CKolkey`
1. [`crispybaccoon/evergarden`](https://github.com/crispybaccoon/evergarden):
    - Owner name changed: `crispybaccoon` -> `comfysage`
1. [`gnikdroy/projections.nvim`](https://github.com/gnikdroy/projections.nvim):
    - Owner name changed: `gnikdroy` -> `GnikDroy`
1. [`hakonharnes/img-clip.nvim`](https://github.com/hakonharnes/img-clip.nvim):
    - Owner name changed: `hakonharnes` -> `HakonHarnes`
1. [`haringsrob/nvim_context_vt`](https://github.com/haringsrob/nvim_context_vt):
    - Owner name changed: `haringsrob` -> `andersevenrud`
1. [`hkupty/iron.nvim`](https://github.com/hkupty/iron.nvim):
    - Owner name changed: `hkupty` -> `Vigemus`
1. [`kvrohit/mellow.nvim`](https://github.com/kvrohit/mellow.nvim):
    - Owner name changed: `kvrohit` -> `mellow-theme`
1. [`kyazdani42/nvim-tree.lua`](https://github.com/kyazdani42/nvim-tree.lua):
    - Owner name changed: `kyazdani42` -> `nvim-tree`
1. [`kyazdani42/nvim-web-devicons`](https://github.com/kyazdani42/nvim-web-devicons):
    - Owner name changed: `kyazdani42` -> `nvim-tree`
1. [`maxmx03/FluoroMachine.nvim`](https://github.com/maxmx03/FluoroMachine.nvim):
     - Repository name changed: `FluoroMachine.nvim` -> `fluoromachine.nvim`
1. [`mickael-menu/zk-nvim`](https://github.com/mickael-menu/zk-nvim):
    - Owner name changed: `mickael-menu` -> `zk-org`
1. [`nkakouros/scrollofffraction.nvim`](https://github.com/nkakouros/scrollofffraction.nvim):
    - Owner name changed: `nkakouros` -> `nkakouros-original`
1. [`ostralyan/scribe.nvim`](https://github.com/ostralyan/scribe.nvim):
    - Owner name changed: `ostralyan` -> `Ostralyan`
1. [`phaazon/mind.nvim`](https://github.com/phaazon/mind.nvim):
    - Owner name changed: `phaazon` -> `hadronized`
1. [`sekke276/dark_flat.nvim`](https://github.com/sekke276/dark_flat.nvim):
    - Owner name changed: `sekke276` -> `uncleTen276`
1. [`shaeinst/roshnivim-cs`](https://github.com/shaeinst/roshnivim-cs):
    - Owner name changed: `shaeinst` -> `Abstract-IDE`
     - Repository name changed: `roshnivim-cs` -> `Abstract-cs`
1. [`themercorp/themer.lua`](https://github.com/themercorp/themer.lua):
    - Owner name changed: `themercorp` -> `ThemerCorp`
1. [`windwp/nvim-spectre`](https://github.com/windwp/nvim-spectre):
    - Owner name changed: `windwp` -> `nvim-pack`
1. [`xiyaowong/nvim-transparent`](https://github.com/xiyaowong/nvim-transparent):
     - Repository name changed: `nvim-transparent` -> `transparent.nvim`
1. [`yashguptaz/calvera-dark.nvim`](https://github.com/yashguptaz/calvera-dark.nvim):
    - Owner name changed: `yashguptaz` -> `niyabits`
1. [`yazeed1s/minimal.nvim`](https://github.com/yazeed1s/minimal.nvim):
    - Owner name changed: `yazeed1s` -> `Yazeed1s`
1. [`yazeed1s/oh-lucy.nvim`](https://github.com/yazeed1s/oh-lucy.nvim):
    - Owner name changed: `yazeed1s` -> `Yazeed1s`
1. [`zeioth/heirline-components.nvim`](https://github.com/zeioth/heirline-components.nvim):
    - Owner name changed: `zeioth` -> `Zeioth`

**Comment by m15a** [comment]
That's all.

**Comment by tversteeg** [comment]
Thanks a ton, I appreciate the effort!
