### ISSUE TITLE
Add https://github.com/al1-ce/just.nvim in Code runner

### ISSUE THREAD

**Issue by al1-ce** [rockerBOO/awesome-neovim#1209]
https://github.com/al1-ce/just.nvim is a task runner for https://github.com/casey/just

**Comment by mosheavni** [comment]
the PR doesn't conform to the template. please follow https://github.com/rockerBOO/awesome-neovim/blob/main/CONTRIBUTING.md

**Comment by al1-ce** [comment]
Oh, sorry. I'll change it a bit later

**Comment by al1-ce** [comment]
Made a PR #1213
