### ISSUE TITLE
Add `nvim-java/nvim-java`

### ISSUE THREAD

**Issue by DragonScarlet** [rockerBOO/awesome-neovim#1244]
Add  [nvim-java/nvim-java](https://github.com/nvim-java/nvim-java) in Programming Languages Support

**Comment by mosheavni** [comment]
Please follow https://github.com/rockerBOO/awesome-neovim/blob/main/CONTRIBUTING.md

**Comment by li-lay** [comment]
@DragonScarlet you can close this issue now! I've made a pr added `nvim-java/nvim-java`
