### ISSUE TITLE
Add IconicFonts

### ISSUE THREAD

**Issue by mdSlash** [rockerBOO/awesome-neovim#1283]
Hi there! I’ve created patched fonts with over 60,000 icons specifically for TUI projects. Can I submit a pull request to include [IconicFonts](https://github.com/iconicFonts/iconic-fonts) repository in Awesome Neovim?

**Comment by thetic** [comment]
https://github.com/rockerBOO/awesome-neovim/blob/main/.github/pull_request_template.md

**Comment by mdSlash** [comment]
Where should I place it? Should I create a new header called "Patched Fonts", or put it somewhere else?

**Comment by thetic** [comment]
I think [this](https://github.com/rockerBOO/awesome-neovim/blob/main/.github/pull_request_template.md?plain=1#L7) means no

**Comment by mdSlash** [comment]
OK, thanks.
