### ISSUE TITLE
Add `back-to-top` button

### ISSUE THREAD

**Issue by IshmamAbir** [rockerBOO/awesome-neovim#1338]
Add a URL that redirects to the `contents` anchor at the end of a header-categorized list.
It will make it much easier to redirect to the content.
That option is available with **Awesome-Go**([avelino/awesome-go](https://github.com/avelino/awesome-go)). Check to see if it can also be implemented here.

**Comment by tversteeg** [comment]
Good idea! Any PRs are welcome!

**Comment by IshmamAbir** [comment]
Thanks. Created a pr #1342 for this issue.
