### ISSUE TITLE
Find alternative to VimAwesome

### ISSUE THREAD

**Issue by enderger** [rockerBOO/awesome-neovim#150]
Unfortunately, it appears as though the VimAwesome project is dead. Their repo has little activity and, as of 3 days ago, the site is down. We probably should consider pointing people to another source, at least until the site returns.

**Comment by tversteeg** [comment]
Agreed, thanks for bringing it up.
Do you have any ideas about an alternative project?

**Comment by enderger** [comment]
Unfortunately, I was only able to find [this shortlist](https://github.com/akrawchyk/awesome-vim#tools).

**Comment by enderger** [comment]
Actually, upon further research another few options might be [vim-pi](https://bitbucket.org/vimcommunity/vim-pi/src/master/) and the [GitHub Topic](https://github.com/topics/vim-plugins)

**Comment by rockerBOO** [comment]
It could be possible the website returns. Seems to be a DNS issue currently. I think more ideally a new maintainer or list owner can take over.

- Add a note that vimawesome is down and the DNS issue. (https://github.com/vim-awesome/vim-awesome/issues/396)

Github topic is bad UX in general but at least shows most popular (in terms of stars). Also limited to only those on github. 

- We can add it as an additional source. 

That shortlist is difficult as there is no context (besides the title) to what the plugins do. 

- We can add it as an additional source. 

vim-pi I couldn't figure out quickly where the list would be there. Also hasn't been updated in awhile. 

---

- We can add https://nvim-awesome.vercel.app/ as an additional source. They have included awesome-neovim and vim plugins.

**Comment by enderger** [comment]
> It could be possible the website returns. Seems to be a DNS issue currently. I think more ideally a new maintainer or list owner can take over.
> 
> * Add a note that vimawesome is down and the DNS issue. ([What happened to the server? vim-awesome/vim-awesome#396](https://github.com/vim-awesome/vim-awesome/issues/396))
> 
> Github topic is bad UX in general but at least shows most popular (in terms of stars). Also limited to only those on github.
> 
> * We can add it as an additional source.
> 
> That shortlist is difficult as there is no context (besides the title) to what the plugins do.
> 
> * We can add it as an additional source.
> 
> vim-pi I couldn't figure out quickly where the list would be there. Also hasn't been updated in awhile.
> 
> * We can add https://nvim-awesome.vercel.app/ as an additional source. They have included awesome-neovim and vim plugins.

Great! As for vim-pi, it appears to be dead as well. It’s linked in Nixpkgs, and I forgot where the update times were on BitBucket.

**Comment by closingin** [comment]
Hello everyone,

Just so you know, the VA website is still up, it's just that their domain name has been hijacked (I think someone forgot to renew it). I explained how to workaround it in [the related issue](https://github.com/vim-awesome/vim-awesome/issues/396#issuecomment-878154048). :slightly_smiling_face:

**Comment by sophiebits** [comment]
For what it's worth, we've restored vimawesome.com and plan to keep it online.

**Comment by rockerBOO** [comment]
@sophiebits great to hear, thanks!

Added the short list https://github.com/akrawchyk/awesome-vim#tools to the README
