### ISSUE TITLE
About fonts

### ISSUE THREAD

**Issue by FrenzyExists** [rockerBOO/awesome-neovim#205]
Hi! Sorry for opening this issue, just had a question:

Does this project would accept PRs that includes fonts?
The reason I ask is because I think that fonts come into great play in editors, including neovim, not only it could greatly improve the aesthetic of it, but also, some fonts may be better for readibility than others.

For example, there's this repo that has bitmap fonts, pixelart style:
https://github.com/turquoise-hexagon/fonts

Or this other font, which is picking a lot popularity and has a vector version:
https://github.com/slavfox/Cozette

**Comment by rockerBOO** [comment]
I think ultimately they are not specific to Neovim. I want things to be specific as there are already lists for vim plugins that work for Neovim but we don't list them to allow some distinction. Also fonts are more linked to your terminal, as you can't change font for Neovim specifically. 

I think this would make for a good separate list or post about fonts that work great for text editing.  I personally hadn't heard of these fonts so some more exposure would be good.

**Comment by FrenzyExists** [comment]
That sounds reasonable. If you ever open a repo about fonts, I'll be glad to share the fonts repos I know around :+1:
