### ISSUE TITLE
Is it fine to replace a plugin with a fork?

### ISSUE THREAD

**Issue by NTBBloodbath** [rockerBOO/awesome-neovim#218]
Hey, to give a bit of context about this question I'll explain a bit.

I recently made a fork of galaxyline and I'll be maintaining it for a while, it's the only active fork of this awesome statusline. Merged some PRs on it, added some new features and fixed some bugs.

So I was wondering if I should replace the glepnir's link in this list with my fork because mine is the maintained one right now.

Regards

**Comment by tversteeg** [comment]
If @glepnir also agrees with it (so doesn't respond) it's fine with me.

**Comment by tversteeg** [comment]
Seems like they don't respond, so you can replace it whenever you want.

**Comment by NTBBloodbath** [comment]
Sure thing, thanks
