### ISSUE TITLE
Adding 'mini.nvim'

### ISSUE THREAD

**Issue by echasnovski** [rockerBOO/awesome-neovim#274]
I would like to ask if it is OK to add references to my [mini.nvim](https://github.com/echasnovski/mini.nvim) plugin to the list. It is a collection of modules, each can be considered as a *separate independent sub-plugin*. So there are 'base16', 'completion', 'comment', etc. Currently there are 15 modules in total.
Ideally I would like to add almost all of them something like this (in appropriate sections of the list):

- [mini.surround](https://github.com/echasnovski/mini.nvim#minisurround) - module of [echasnovski/mini.nvim](https://github.com/echasnovski/mini.nvim) for working with text surroundings (add, delete, replace, find, highlight) which fully supports dot-repeat.

Is it OK to do it like that?

**Comment by tversteeg** [comment]
Sure, looks good to me. You can open a PR for that.
