### ISSUE TITLE
blackCauldron7/surround.nvim is not available

### ISSUE THREAD

**Issue by Mephistophiles** [rockerBOO/awesome-neovim#315]
Repo https://github.com/blackCauldron7/surround.nvim is no longer available. Maybe the user has been deleted?

**Comment by Mephistophiles** [comment]
Does anyone have a full history fork? I have only a shallow clone via packer.

**Comment by Mephistophiles** [comment]
My local part starts from
```
commit 59a0ef7d7f8da05f9e03075186b6de754e85c42c
Author:     blackCauldron7 <blackCauldron7@protonmail.com>
AuthorDate: Thu Dec 16 11:38:03 2021 +0530
Commit:     blackCauldron7 <blackCauldron7@protonmail.com>
CommitDate: Thu Dec 16 11:40:30 2021 +0530

    add new option space_on_closing_char
---
 .gitignore              |   2 +
 README.md               | 113 ++++++++
 lua/surround/init.lua   | 769 +++++++++++++++++++++++++++++++++++++++++++++++++++++++
 lua/surround/parser.lua | 379 +++++++++++++++++++++++++++
 lua/surround/utils.lua  | 220 ++++++++++++++++
 plugin/surround.vim     |   3 +
 6 files changed, 1486 insertions(+)
 ```

It turns out a gap in the history of about 2 months.

how to export history from here: https://sourcegraph.com/github.com/blackCauldron7/surround.nvim

**Comment by rockerBOO** [comment]
Note there was no license associated with this code so generally would full copyright of blackCauldron7. Copying and reproducing may be a legally bad idea. I do not feel personally this was intentional though but be aware.

**Comment by Mephistophiles** [comment]
Then it makes sense to remove this repository from the list?

full repo: https://github.com/Mephistophiles/surround.nvim

**Comment by metalelf0** [comment]
I sincerely hope the original author is ok.

**Comment by vdwees** [comment]
Is there a canonical fork yet, or is it still to be decided?
