### ISSUE TITLE
Adding Neo-Tree

### ISSUE THREAD

**Issue by zenkimoto** [rockerBOO/awesome-neovim#325]
I recently came across an awesome new tree plugin that I think would be great to be included.  [Neo-tree](https://github.com/nvim-neo-tree/neo-tree.nvim) is a fairly new plugin.  I can create a PR to add it if it is ok.

Thanks!

**Comment by tversteeg** [comment]
You are welcome to create a PR for that!

**Comment by zenkimoto** [comment]
@tversteeg - Here it is.
https://github.com/rockerBOO/awesome-neovim/pull/326
