### ISSUE TITLE
Indicating viml vs lua stuff

### ISSUE THREAD

**Issue by rgnkn** [rockerBOO/awesome-neovim#361]
Hi @all,

I'd like to ask if it may be possible to indicate on your awesome `awesome-neovim` repo such plugins, etc. which are using viml vs those which are lua (maybe also mentioning fennel stuff).

For me it would be interesting to see this on your page without the need to check the referenced repo.

**Comment by rockerBOO** [comment]
I think this would be a good idea but I don't think it will work for this list directly. Too hard to update all the items, hard to distinguish these manually, more upkeep if the plugins update their code to use more lua and/or vimscript. 

In practice, in my experience, most Neovim specific plugins are already primarily using lua and only a few are using vimscript primarily. Fennel or teal also can be cool to see but hard to manage as they may add teal or fennel or use the resulting code and stop using these.  Some may use third party RPC connections as well, which makes it a little harder convey. 

This seems better for a third party to use the GitHub API or other tooling that can automatically view the vimscript, lua, or other language usage in the code. This helps keep submissions simple as a list for plugin developers to add and keeps it updated as things change. A few other tools are using this list to populate additional information and I feel this is a good balance for the time being. If you make a tool to view this information, we can add it to the Resource section.
