### ISSUE TITLE
Add crusj/structrue-go.nvim

### ISSUE THREAD

**Issue by crusj** [rockerBOO/awesome-neovim#378]
A better structured display of golang symbol information
[structrue-go](https://github.com/crusj/structrue-go.nvim)

**Comment by jakewvincent** [comment]
Just FYI, you'll need to make a PR to add a plug-in to the list: [CONTRIBUTING.md](https://github.com/rockerBOO/awesome-neovim/blob/main/CONTRIBUTING.md)

**Comment by crusj** [comment]
> Just FYI, I think you'll need to make a PR to add a plug-in to the list: [CONTRIBUTING.md](https://github.com/rockerBOO/awesome-neovim/blob/main/CONTRIBUTING.md)

Ok
