### ISSUE TITLE
Link to nvim-lua/wishlist?

### ISSUE THREAD

**Issue by wbthomason** [rockerBOO/awesome-neovim#5]
I'm not sure if this is appropriate for this repo, but there's another repo at https://github.com/nvim-lua/wishlist that's collecting ideas for Neovim plugins people would like to have. Maybe it would make sense to link to that repo here, in case people come looking for a plugin/class of plugin and don't find a good option?

**Comment by rockerBOO** [comment]
Thanks for the suggestion! Added to the list top of the list.
