### ISSUE TITLE
About repo's order

### ISSUE THREAD

**Issue by BreezyMain** [rockerBOO/awesome-neovim#504]
could you resort to the repositories according to their starts(or something else)?

**Comment by tversteeg** [comment]
Unfortunately this isn't allowed in the current format, maybe that's possible with a third party website.

**Comment by BreezyMain** [comment]
> Unfortunately this isn't allowed in the current format, maybe that's possible with a third party website.

Maybe a python crawler can be written to solve this problem.

**Comment by Weissle** [comment]
Maybe this website can help you. https://neovimcraft.com/
Sorting the repositories according to their stars, updating data or something change frequently may not be a good idea.
