### ISSUE TITLE
A place for TWiN

### ISSUE THREAD

**Issue by phaazon** [rockerBOO/awesome-neovim#505]
Hey!

I’m the author of https://this-week-in-neovim.org, which I wrote the webserver and bootstrapped the contents. I’m looking for contributors but until I get enough, I’m also writing most of the contents. Anyway, I was wondering whether you would be interested to add a special mention to consolidate effort? I will obviously add a mention to this repository in TWiN as well! 🙂 

Cheers! 🍷 🍻

**Comment by tversteeg** [comment]
Great job on the website, it looks really good!

I think a mention in the 'Resource' section would be the right place for this. A PR would be greatly appreciated.

**Comment by phaazon** [comment]
I will make one then! Thanks!
