### ISSUE TITLE
`Plugin` subcategories re-organization

### ISSUE THREAD

**Issue by T-727** [rockerBOO/awesome-neovim#557]
Would make quickly finding categories easier imo, especially when taking a look from something like the mobile app (no search-bar).
If you agree with this I can make a PR no problem.

**Comment by tversteeg** [comment]
I'm not entirely sure if I agree with this, on the one hand it would make it better for searching through the categories. But I think that some categories make sense to follow each other up, such as: `Neovim Lua Development` & `Fennel`, `Tabline` & `Statusline`.

I do think the current list of categories is a mess though, but I would rather remove some categories than sort them alphabetically.

**Comment by T-727** [comment]
Fair points. having related categories in "sub-subcategories" does sound like a good plan to me, although some already have subcategories like `LSP`, `Colorscheme` and `Motion`, would nesting that deep be a bad idea?
And yeah removing tiny categories where it makes sense is also a good idea.

**Comment by tversteeg** [comment]
I don't think nesting is a bad idea, for me it makes it easier to find something.

**Comment by T-727** [comment]
Alrighty then 🙂. I suppose I'll come up with a draft and come back once I have something, sounds good?

**Comment by T-727** [comment]
[v1](https://github.com/T-727/awesome-neovim/commit/40a1698ccdc87648ce9c05662486b79e9c30898e).
No particular pattern exactly, just grouping some stuff together where I thought it *somewhat* made sense.
And not complete by any means, just getting an idea of what it would look like.
I'd  love to hear your feedback :)

**Comment by tversteeg** [comment]
Looking good so far! Can you make it a draft PR so some commentary is easier to give?
