### ISSUE TITLE
What category for bibliography management plugin

### ISSUE THREAD

**Issue by jghauser** [rockerBOO/awesome-neovim#567]
I recently published a first version of [papis.nvim](https://github.com/jghauser/papis.nvim). It's a plugin that enables interacting with bibliography databases created with [papis](https://github.com/papis/papis). It's mostly meant for academics who who use neovim to write prose (but it's not limited to markdown/latex file formats). I'm not sure what category would be a good for it -- do you have any suggestions?

**Comment by rockerBOO** [comment]
Possibly Note-taking. Or maybe we should redo the markdown/latex category to be Prose/Scientific Writing or something. Keep it behavior based instead of language specific.

**Comment by jghauser** [comment]
Thanks for the input! I'll go with note-taking for now even though teeechnically, it's not just for note-taking. If at some point we re-organise things to have a scientific writing category, then i'll move it. :)
