### ISSUE TITLE
Add better-escape.vim

### ISSUE THREAD

**Issue by BigCrow** [rockerBOO/awesome-neovim#640]
Add nvim-zh/better-escape.vim as an altentative to max397574/better-escape.nvim. max397574 has an unresolved issue that moves the cursor to the incorrect position, when the dot command is used to repeat an insert command where you used the plugin to exit. nvim-zh version does not have that issue.
https://github.com/nvim-zh/better-escape.vim

**Comment by tversteeg** [comment]
I'm okay with this if there's consensus that's the better supported version. You're welcome to open a PR!

**Comment by BigCrow** [comment]
I don't know if there is a consensus. Both of the plugins has not been updated in a while. The max397574/better-escape.nvim, actually has a more advanced feature, since it allows you to remap the better-espace sequnce to any function (so it's issue could be solved that way too). The nvim-zh/better-escape.vim on the other hand works properly with the default configuration.

**Comment by tversteeg** [comment]
Actually closing this issue since the one you propose is not a Neovim specific plugin.
