### ISSUE TITLE
Update `nvim-ts-rainbow` repo

### ISSUE THREAD

**Issue by mrjones2014** [rockerBOO/awesome-neovim#652]
The original maintainer [archived the repo and is no longer maintaining it](https://github.com/p00f/nvim-ts-rainbow).

I'm taking up maintenance in a new fork. This repo should point to the maintained repo: https://github.com/mrjones2014/nvim-ts-rainbow

**Comment by thetic** [comment]
Submit a PR.

**Comment by mrjones2014** [comment]
Yup I plan to. Haven’t gotten to it yet
