### ISSUE TITLE
Add plugins to the list 📑

### ISSUE THREAD

**Issue by farias-hecdin** [rockerBOO/awesome-neovim#653]
Hello friends, how are you?
I really love ❤ your project, it has helped me a lot to create my personal Neovim configuration.

There are some plugins that I use that are not yet listed and I would like -please- that you add them to the list to support the developers. 👍

## File explorer

* [obaland/vfiler.vim](https://github.com/obaland/vfiler.vim): File explorer plugin for Vim/Neovim.
* [EdvinVikstrom/filetree.nvim](https://github.com/EdvinVikstrom/filetree.nvim): A file tree plugin for Neovim written in Lua.

## Editing Support

* [tmillr/sos.nvim](https://github.com/tmillr/sos.nvim): Never manually save/write a buffer again!

## Indent

* [LucasTavaresA/simpleIndentGuides.nvim](https://github.com/LucasTavaresA/simpleIndentGuides.nvim): Indentation guides using the builtin variables.

## Utility

* [j-morano/buffer_manager.nvim](https://github.com/j-morano/buffer_manager.nvim): A simple plugin to easily manage Neovim buffers.

## Search

* [s1n7ax/nvim-search-and-replace](https://github.com/s1n7ax/nvim-search-and-replace): Absolutly minimal plugin to search and replace multiple files in current working directory.
* [roobert/search-replace.nvim](https://github.com/roobert/search-replace.nvim): A Neovim search and replace plugin that builds on the native search and replace experience.

**Comment by tversteeg** [comment]
You're welcome to create PRs for each Neovim specific plugin! The plugins also for Vim don't belong in this repo.

**Comment by farias-hecdin** [comment]
Done, I have already created a PR. 👍
