### ISSUE TITLE
jameshiew/nvim-magic - Framework for integrating AI code assistance. IsNo Longer Being Maintained

### ISSUE THREAD

**Issue by dedguy21** [rockerBOO/awesome-neovim#699]
This plugin is no longer being maintained per github page

[jameshiew/nvim-magic](https://github.com/jameshiew/nvim-magic) - Framework for integrating AI code assistance.

**Comment by tversteeg** [comment]
You can create a PR for removing it, thanks.

**Comment by dedguy21** [comment]
That actually was what I was scrolling for. I think that a section for AI is very appropriate. I'm using GitHub's copilot ATM myself.

**Comment by tversteeg** [comment]
Sure, an AI section makes sense. Any PRs adding that are very welcome!

**Comment by dedguy21** [comment]
PR submitted regarding this issue.
