### ISSUE TITLE
Feat: Add markdown-preview.nvim by iamcco

### ISSUE THREAD

**Issue by 21st-centuryman** [rockerBOO/awesome-neovim#702]
With 4.5 stars I think we should add the following: https://github.com/iamcco/markdown-preview.nvim

**Comment by tversteeg** [comment]
You're welcome to create a PR for this!

**Comment by 21st-centuryman** [comment]
Oh lmao I was already on it!

**Comment by wsdjeg** [comment]
@tversteeg why `markdown-preview.nvim` was removed???

**Comment by tversteeg** [comment]
> @tversteeg why `markdown-preview.nvim` was removed???

No idea, I didn't remove it, at least not on purpose.
