### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by ndsvw** [rockerBOO/awesome-neovim#772]
Hello, I found 2 broken hyperlinks:
- [ ] https://github.com/EdvinVikstrom/filetree.nvim (file: README.md, status code: 404)
- [x] https://github.com/CanKolay3499/CNvim (file: README.md, status code: 404)

**Comment by tversteeg** [comment]
Hi, you're welcome to create a PR to remove them.

**Comment by korbexmachina** [comment]
I just created a PR to remove the broken link to EdvinVikstrom/filetree.nvim, I had a look to make sure the repo had not been renamed. It seems like it was either deleted or made private.

**Comment by yagiziskirik** [comment]
As @korbexmachina said, I also tried to find the `EdvinVikstrom/filetree.nvim` as well, I can confirm that it is deleted or made private. WaybackMachine shows and entry on [April 18, 2022](https://web.archive.org/web/20220418213501/https://github.com/EdvinVikstrom/filetree.nvim) but as of snapshot March 27, 2023, it is gone. Couldn't find it on GitHub as well.

**Comment by tversteeg** [comment]
Please create a PR so it can be discussed there as well.
