### ISSUE TITLE
galaxyline is a fork

### ISSUE THREAD

**Issue by EJammy** [rockerBOO/awesome-neovim#826]
Is this a mistake? It looks like the original project is still maintained

Edit: I realized the maintainer took some time off... Not sure what's the best to do here

**Comment by 3719e04** [comment]
This issue has been addressed in #218. Feel free to close.

**Comment by EJammy** [comment]
But the original one is active again. Maybe include both?

**Comment by 3719e04** [comment]
> Maybe include both?

I think that will confuse many users.

My observation is that `glepnir` (original author of galaxyline.nvim) is not focusing on galaxyline right now.
