### ISSUE TITLE
Adding `xmake.nvim` but I don't know where to put it

### ISSUE THREAD

**Issue by Mythos-404** [rockerBOO/awesome-neovim#845]
Makes it easier to use the [`xmake`](https://xmake.io) build tool in neovim.

Plugin address: [xmake.nvim](https://github.com/Mythos-404/xmake.nvim)

**Comment by SeleneCosmia** [comment]
I would say it probably belongs in the [Utility](https://github.com/rockerBOO/awesome-neovim#utility) section.
