### ISSUE TITLE
Maintance

### ISSUE THREAD

**Issue by NTBBloodbath** [rockerBOO/awesome-neovim#85]
Hi, hope you are well.

This issue is made to reflect the lack of maintenance of the repository (speaking of handling PRs and issues). Since you may be busy, it would be good to think about adding other contributors who can also take care of the maintenance.

I hope it's taken into consideration :slightly_smiling_face:

**Comment by rockerBOO** [comment]
Yes, I would be interested in additional maintainers for this list.

**Comment by tversteeg** [comment]
I would like to offer myself as a maintainer.

**Comment by LuisxSullivaN** [comment]
@tversteeg So would I

**Comment by andersevenrud** [comment]
I can also help out in. I'm in CEST timezone.
