### ISSUE TITLE
packer.nvim is unmaintained

### ISSUE THREAD

**Issue by ryanknutson** [rockerBOO/awesome-neovim#852]
the packer.nvim plugin manager is listed as being unmaintained currently on [its repository](https://github.com/wbthomason/packer.nvim)

The developer recommends people use [lazy.nvim](https://github.com/folke/lazy.nvim) (included in your list at the bottom), or for those who don't mind a little instability, [pckr.nvim](https://github.com/lewis6991/pckr.nvim).

Consider adding a notice of it's unmaintained status :)

**Comment by tversteeg** [comment]
You're welcome to create a PR for this.
