### ISSUE TITLE
Where to place a plugin focussed on grepping (find)?

### ISSUE THREAD

**Issue by mangelozzi** [rockerBOO/awesome-neovim#888]
I would like to add my plugin [rgflow.nvim](https://github.com/mangelozzi/rgflow.nvim), it is primary about performing a [RipGrep](https://github.com/BurntSushi/ripgrep) with interface that is very close to the CLI, yet intuitive, and place those results in the QuickFix list, and give you some extra quickfix tools for editing the quickfix list.

I see there is a section for searching, but its more about `/` and `?` kind of searches. There is also a section for fuzzy finders. But there isnt a section for `grep` like tools.

Should I create a section something like `Find` or `Find in Files`  ?

**Comment by tversteeg** [comment]
There's alread a Search category: https://github.com/rockerBOO/awesome-neovim#search

**Comment by mangelozzi** [comment]
> I see there is a section for searching, but its more about `/` and `?` kind of searches.

I don't know if you saw this part of my post: `I see there is a section for **searching**, but its more about / and ? kind of searches. ` ?
