### ISSUE TITLE
Add `salorak/whaler.nvim` plugin.

### ISSUE THREAD

**Issue by SalOrak** [rockerBOO/awesome-neovim#935]
Add [salorak/whaler.nvim](https://github.com/salorak/whaler.nvim) in the Utility section.

It can be placed in multiple sections. Whalers uses Telescope UI to fuzzy find between directories and opens (optionally) the configured File Explorer. It is NOT a replacement for a File explorer. 

I suggest either adding in the Utility, Fuzzy Finder or Project section.

**Comment by GCBallesteros** [comment]
Can be closed. Whaler was added in commit 9da15278c
